# -*- mode: ruby -*-
# vi: set ft=ruby :

# (c) 2014 Eyefodder, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "eyefodder/precise64-utf8"
  config.vm.host_name = 'spex-jenkins'

  config.vm.provider 'virtualbox' do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.name = 'spex-jenkins'
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 80, host: 8081

  config.vm.synced_folder "../puppet", "/etc/puppet"
  config.vm.provision 'shell', path: 'install_puppet_modules.sh'

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path =  "../puppet/manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = '../puppet/modules'
    puppet.hiera_config_path = "../puppet/hiera.yaml"
    puppet.working_directory = "/etc/puppet"
  end


end
